version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: retail-mono-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3307:3306'
    volumes:
      - ./docker/data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  member-service:
    build:
      context: ./member-service
    container_name: retail-member
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/retail_member?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"

  product-service:
    build:
      context: ./product-service
    container_name: retail-product
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/retail_product?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"

  gateway-service:
    build:
      context: ./gateway-service
    container_name: retail-gateway
    depends_on:
      - member-service
      - product-service
    ports:
      - "8080:8080"
