#server:
#  port: 8000
#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: member-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/members/**
#          filters:
#            - RemoveResponseHeader=Server
#        - id: product-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/products/**
#          filters:
#            - RemoveResponseHeader=Server
#
#      default-filters:
#        - RemoveResponseHeader=Server
#
#
#jwt:
#  secret: my-super-secret-key-for-retail-monorepo
#  expiration: 3600000

#---

server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member-service
#              uri: http://localhost:8081
              uri: http://member-service:8081
              predicates:
                - Path=/api/members/**
              filters:
                - RemoveResponseHeader=Server

            - id: product-service
#              uri: http://localhost:8082
              uri: http://product-service:8082
              predicates:
                - Path=/api/products/**
              filters:
                - RemoveResponseHeader=Server

          default-filters:
            - RemoveResponseHeader=Server

jwt:
  secret: my-super-secret-key-for-retail-monorepo
  expiration: 3600000


