spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member-service
              uri: http://member-service:8081
              predicates:
                - Path=/api/members/**
              filters:
                - RemoveResponseHeader=Server

            - id: product-service
              uri: http://product-service:8082
              predicates:
                - Path=/api/products/**
              filters:
                - RemoveResponseHeader=Server

          default-filters:
            - RemoveResponseHeader=Server

jwt:
  secret: my-super-secret-key-for-retail-monorepo
  expiration: 3600000
